name: screenshots
on:
  push:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://datastudio.google.com/embed/reporting/c14a5cfc-cab7-4812-848c-0369173148ab/page/ZwmOB
        devices: iPad Pro
        noDesktop: true
    - uses: actions/upload-artifact@v2
      with:
        name: screen
        path: screenshots
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add --all
        git commit -am "add data"
        git push
